import Head from "next/head";
import styles from "styles/Home.module.css";

import Header from "components/header";
import { useRouter } from "next/router";
import { GetServerSideProps } from "next";

export default function Post() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />

        <p>Content for page /post/{router.query.id}.js</p>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  return { props: { hello: "world" } };
};
