import Head from "next/head";
import styles from "../styles/Home.module.css";

import Header from "../components/header";
import { GetServerSideProps } from "next";
import { useState } from "react";
import dynamic from "next/dynamic";

const Welcome = dynamic(() => import("../components/welcome"));

export default function Home() {
  const [show, setShow] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />

        <div>
          <p>Content for page /index.js</p>
          <button onClick={() => setShow(true)}>Open hello</button>
          {show && <Welcome />}
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  return { props: { hello: "world" } };
};
