import Head from "next/head";
import styles from "../styles/Home.module.css";

import Header from "../components/header";
import { GetServerSideProps } from "next";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />

        <p>Content for page /index.js</p>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  return { props: { hello: "world" } };
};
