import Head from "next/head";
import styles from "../styles/Home.module.css";

import Header from "../components/header";
import Link from "next/link";
import { GetServerSideProps } from "next";

export default function Posts() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />

        <p>Content for page /posts.js</p>
        <ul>
          <li>
            <Link href={`/post/1`}>Post 1</Link>
          </li>
          <li>
            <Link href={`/post/2`}>Post 2</Link>
          </li>
          <li>
            <Link href={`/post/3`}>Post 3</Link>
          </li>
          <li>
            <Link href={`/post/4`}>Post 4</Link>
          </li>
        </ul>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  return { props: { hello: "world" } };
};
